CIS-1.1 - 4.03 Ensure "Block Project-wide SSH keys" is enabled for VM instances
forseti-security/policy-library pull request #405
Opened 2021-10-12 08:42 UTC by palani-ram-google-partner

CIS-1.1 - 4.03 Ensure "Block Project-wide SSH keys" is enabled for VM instances

2021-10-12 08:44 UTC, palani-ram-google-partner commented
@morgante Please review this PR. All your review comments are fixed in this PR.

This is replacement PR for the below old PR.
https://github.com/GoogleCloudPlatform/policy-library/pull/401

2021-10-12 21:35 UTC, morgante requested changes
Thanks for contributing!

2021-10-14 05:04 UTC, morgante requested changes

2021-10-14 05:04 UTC, morgante commented on validator/compute_block_ssh_keys_test.rego
> +	test_utils.check_test_violations_resources(fixture_compute_instance_violation, [fixture_constraints], template_name, expected_resource_names)
This is a duplicate of line 43/44. You can just remove these 2 lines if you want.

2021-10-21 16:39 UTC, morgante commented on validator/compute_block_ssh_keys_test.rego
> +	test_utils.check_test_violations_resources(fixture_compute_instance_violation, [fixture_constraints], template_name, expected_resource_names)
Each test block should really only deal with a single fixture. Suggest removing these lines in the future.

2021-10-21 16:40 UTC, merged